include:
  - project: 'josmase/infrastructure/ci-templates'
    ref: 'v3.0.5'
    file: 'pipelines/standard.yml'

tag-release:
  extends: .docker-build
  variables:
    IMAGE_TAG: $CI_COMMIT_TAG
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'

variables:
  DEPLOY_REPO_PATH: "$CI_PROJECT_PATH"
  MANIFEST_PATH: "deploy/base/deployment.yaml"
  IMAGE_PATH: "spec.template.spec.containers[0].image"
