name: Nightly Patch Version Bump

on:
  schedule:
    - cron: "0 0 * * *" # Runs once a day at midnight UTC
  workflow_dispatch: # manual trigger

jobs:
  automatic-changelog:
    uses: josmase/workflows/.github/workflows/automatic-changelog.yaml@main
    secrets:
      token: ${{ secrets.AUTO_DEPLOY_PAT }}
