name: Pull Request Validation

on:
  pull_request:
    branches:
      - "main"

jobs:
  build:
    uses: https://github.com/josmase/workflows/docker-build.yaml
    with:
      runner: downloader
      registry_url: ${{ vars.REGISTRY_URL }}
      registry_username: ${{ secrets.REGISTRY_USERNAME }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
      dockerfile: ./Dockerfile
      context: .
