name: Pull Request Validation

on:
  pull_request:
    branches:
      - "main"

jobs:
  build:
    name: pull-request-validation
    uses: josmase/workflows/.github/workflows/docker-build.yaml@main
    with:
      runner: ${{ vars.RUNNER_NAME }}
      registry_url: ${{ vars.REGISTRY_URL }}
    secrets:
      registry_username: ${{ secrets.REGISTRY_USERNAME }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
    permissions:
      contents: read
